search:
  directoryLocation: index
  resultsPerPage: 10
  maxResults: 100

recipe:
  recipeDirectory: ../data/recipes
  authorDirectory: ../data/authors
  recipeImageDirectory: ../data/images
  authorImageDirectory: ../data/author-images